# 属性对应服务注册中心的配置内容，指定服务注册中心的位置。为了在本机上测试区分服务提供方和服务注册中心，使用server.port属性设置不同的端口。
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

# 显示任意的应用信息，默认关闭  springBoot版本：2.7.5 CURRENT  GA如果是更低一些的版本默认是开启的
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'

# 应用端口
server:
  port: 10000
spring:
  # 应用名称
  application:
    name: easy-microservice-gateway
  # 路由的配置
  cloud:
    gateway:
      routes:
        - id: search
          uri: https://bing.com
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/api/search
        - id: easy-microservice-order
          uri: lb://easy-microservice-order
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/queryOrderInfos
  #链路监控
  sleuth:
    sampler:
      # 采样率的概率，100%采样
      probability: 1.0
      # 每秒采样数字最高为1000
      rate: 1000
  zipkin:
    base-url: http://localhost:9411/ # 服务端地址
    sender:
      type: web                      # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据

logging:
  level:
    org.springframework.cloud.sleuth: debug



