management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081
spring:
  application:
    name: nacos-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
