management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 20000
spring:
  application:
    name: nacos-center
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        enabled: true
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        username: nacos
        password: nacos
